# Generated by Django 5.2 on 2025-05-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
    ]
