# Generated by Django 5.2 on 2025-05-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_address_alter_order_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
