# Generated by Django 5.2 on 2025-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_order_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('packing', 'Упаковка'), ('shipped', 'В пути'), ('delivered', 'Доставлен')], default='packing', max_length=20, verbose_name='Статус'),
        ),
    ]
