# Generated by Django 5.2 on 2025-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные при выдаче'), ('card', 'Банковская карта'), ('sbp', 'СБП (Система быстрых платежей)')], default='cash', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
