# Generated by Django 5.2 on 2025-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные при выдаче'), ('card', 'Банковская карта'), ('sbp', 'СБП')], default='cash', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
